accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts.forms import UserLoginForm
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<hash>[0-9A-Za-z_\-]+)/$',
        views.activate, name='activate'),
    url(r'^profile/$', views.create_profile, name='createprofile'),
    url(r'^forgot/$', views.forgot_password, name='forgot'),
    url(r'^password_update/$', views.password_update, name='password_update'),
    url(r'^password_reset/(?P<hash>[0-9A-Za-z_\-]+)/$',
        views.password_reset, name='password_reset'),
    # url(r'^edit-add_line/$', views.edit_profile, name='panel'),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='site/accounts/login.html',
                                     authentication_form=UserLoginForm),
        name='login'),
    url(r'^register/$', views.signup, name='signup'),
    url(r'^add_line/$', views.profile, name='add_line'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^admin/', admin.site.urls),
    # end of authentication for website

]

api/urls.py
from django.urls import path
from rest_framework.authtoken import views as tv

from . import views

app_name = 'api'
urlpatterns = [
    # end of authentication for website
    path('token/', tv.obtain_auth_token, name='token_obtain'),
    path('files/', views.FileList.as_view(), name='files'),

]

djangoHealthAnalytics/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoHealthAnalytics import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^contact-us/$', views.contact, name='contact-us'),
    url(r'^about-us/$', views.about, name='about-us'),
    url(r'^panel/$', views.panel, name='panel'),
    # start of site pages

]

templates/site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>H.M.I.S | {% block title_extension %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {#    <link rel="icon" href="{% static 'images/favicon.ico' %} " type="image">#}
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css ' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-pro/css/fontawesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css ' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra %}{% endblock %}
</head>
<body class="goto-here">

{% block news %}
    {#    <div class="py-1 bg-danger">#}
    {#        <div class="container">#}
    {#            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">#}
    {#                <div class="col-lg-12 d-block">#}
    {#                    <div class="row d-flex">#}
    {#                        <div class="col-md pr-4 d-flex topper align-items-center">#}
    {#                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span#}
    {#                                    class="icon-message"></span></div>#}
    {#                            <span class="text">Beware of the covid-19!!Practise self hygiene,avoid handling money and use mobile banking where possible.Safety starts with you!!</span>#}
    {#                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span#}
    {#                                    class="icon-message"></span></div>#}
    {#                        </div>#}
    {##}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}

{% endblock %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">

    {% block nav %}
        <div class="container">
            <a class="navbar-brand" href="{% url 'accounts:login' %}">Disease prediction System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                    aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>
            {% block formSearch %}{% endblock %}

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">

                    {#                                    <li class="nav-item active"><a href="{% url 'index' %}" class="nav-link">Home</a></li>#}
                    {#                    <li class="nav-item"><a href="{% url 'pages:contact-us' %}" class="nav-link">Contact Us</a></li>#}
                    {#                    <li class="nav-item"><a href="{% url 'pages:about-us' %}" class="nav-link">About Us</a></li>#}





                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'accounts:login' %}"
                               id="dropdown04" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">{{ user.email }}</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">


                                <a class="dropdown-item" href="{% url 'accounts:logout' %}"> <span
                                        class="icon-sign-out"></span>Log out</a>

                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'accounts:login' %}"
                               id="dropdown04" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"><span
                                    class="icon-supervisor_account"></span>Hello,Sign in</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="{% url 'accounts:login' %}"><span
                                        class="icon-sign-in"></span>Login</a>
                                <a class="dropdown-item" href="{% url 'accounts:signup' %}"><span
                                        class="icon-person_add"></span>Register</a>

                            </div>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    {% endblock %}

</nav>


{% block maincontent %}



{% endblock %}

{% block footer %}
{#    <footer class="ftco-footer ftco-section" style="background-color:  #6a359f ">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="mouse">#}
{#                    <a href="#" class="mouse-icon">#}
{#                        <div class="mouse-wheel"><span class="icon-mouse"></span></div>#}
{#                    </a>#}
{#                </div>#}
{#            </div>#}
{#            <div class="row mb-5">#}
{#                <div class="col-md">#}
{#                    <div class="ftco-footer-widget mb-4">#}
{#                        <h2 class="ftco-heading-2">H.M.I.S</h2>#}
{##}
{#                    </div>#}
{#                </div>#}
{##}
{#            </div>#}
{#            <div class="row">#}
{#                <div class="col-md-12 text-center">#}
{##}
{#                    <p>#}
{#                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>#}
{#                        All rights reserved...#}
{#                    </p>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </footer>#}



    <!-- loader -->
{#    <div id="ftco-loader" class="show fullscreen">#}
{#        <svg class="circular" width="48px" height="48px">#}
{#            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4"#}
{#                    stroke="#eeeeee"></circle>#}
{#            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"#}
{#                    stroke="#6a359f"></circle>#}
{#        </svg>#}
{#    </div>#}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/site/panel.html
{% extends 'site/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block extra %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block title_extension %} Panel {% endblock %}
{% block maincontent %}
    <div class="container vh-100">
        <div class="card vh-100">
            <div class="row m-4 align-items-center">
                <form class="form-inline mb-lg-5 " action="{% url 'pages:panel' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group  mr-2">
                        {{ form.disease_name }}

                    </div>
                    <div class="input-group  mr-2">
                        {{ form.location }}

                    </div>

                    <button type="submit" class="btn btn-success btn-lg">Search</button>
                </form>
            </div>
   <div class="row">
               {% for x in file %}
                    <div class="col-12 mb-5 center ftco-animate">
                    {#    				<a href="{{product.image.url}}" class="image-popup">#}
                    <img src="{{ x.image.url }}" class="img-fluid center" alt="{{ x.user.email }}">
                    {#                    </a>#}
                </div>
               {% endfor %}

            </div>
        </div>
    </div>
    <script>
        $(function () {
            $("#datetimepicker1").datetimepicker({
                format: 'DD/MM/YYYY HH:mm',
            });
        });
        $(function () {
            $("#datetimepicker2").datetimepicker({
                format: 'DD/MM/YYYY HH:mm',
            });
        });
    </script>
{% endblock %}
{% block footer %}{% endblock %}

templates/site/success.html
{% extends 'site/base.html' %}
{% load static %}
{% block title_extension %}Operation Successfull{% endblock %}
{% block cart %}
    {{ cart_count }}
{% endblock %}
{% block maincontent %}
    <p>Operation successfull</p>
{% endblock %}