accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts.forms import UserLoginForm
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<hash>[0-9A-Za-z_\-]+)/$',
        views.activate, name='activate'),
    url(r'^profile/$', views.create_profile, name='createprofile'),
    url(r'^forgot/$', views.forgot_password, name='forgot'),
    url(r'^password_update/$', views.password_update, name='password_update'),
    url(r'^password_reset/(?P<hash>[0-9A-Za-z_\-]+)/$',
        views.password_reset, name='password_reset'),
    # url(r'^edit-add_line/$', views.edit_profile, name='panel'),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='site/accounts/login.html',
                                     authentication_form=UserLoginForm),
        name='login'),
    url(r'^register/$', views.signup, name='signup'),
    url(r'^add_line/$', views.profile, name='add_line'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^admin/', admin.site.urls),
    # end of authentication for website

]

api/urls.py
from django.urls import path
from rest_framework.authtoken import views as tv

from . import views

app_name = 'api'
urlpatterns = [
    # end of authentication for website
    path('token/', tv.obtain_auth_token, name='token_obtain'),
    path('files/', views.FileList.as_view(), name='files'),

]

djangoHealthAnalytics/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoHealthAnalytics import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from accounts.models import User, Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(
        attrs={'placeholder': 'example@domain.com', 'style': 'text-align:center'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'eg(Michp@57r13$)', 'style': 'text-align:center'}),
        label='Password')
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'eg(Michp@57r13$)', 'style': 'text-align:center'}),
        label='Password')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Jane', 'style': 'text-align:center'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Doe', 'style': 'text-align:center'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(max_length=254)

    class Meta:
        fields = ('email',)
        widgets = {
            'email': forms.TextInput(attrs={'class': 'myfieldclass'}),
        }


class NewPasswordForm(forms.Form):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'PASSWORD'}), max_length=20,
                                label='PASSWORD')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'PASSWORD CONFIRMATION'}),
                                max_length=20, label='PASSWORD CONFIRMATION')

    class Meta:
        fields = ('password1', 'password2')


class ContactUsForm(forms.Form):
    sender_name = forms.CharField(required=True,
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}))
    sender_mail = forms.EmailField(required=True,
                                   widget=forms.EmailInput(
                                       attrs={'class': 'form-control', 'placeholder': 'Your Email'}))
    mail_subject = forms.CharField(required=True,
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control', 'placeholder': 'Your Subject'}))

    mail_message = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Message here....', "rows": 7, "cols": 30}))


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(widget=forms.TextInput(
        attrs={'style': 'text-align:center',
               'placeholder': 'example@domain.com', 'id': 'hello'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'style': 'text-align:center',
            'placeholder': 'PASSWORD',
        }
    ))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address']
        widgets = {
            'address': forms.TextInput(attrs={'placeholder': 'Address'}),

        }


class ProfileAccountForm(forms.ModelForm):
    email = forms.EmailField(max_length=254, disabled=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from accounts.forms import SignUpForm, ForgotPasswordForm, ProfileForm, ProfileAccountForm, NewPasswordForm
from accounts.models import User
from djangoHealthAnalytics.extras import split_domain_ports
from pages.models import Images
from .tokens import account_activation_token


# @login_required(login_url='site/accounts:login')
# def panel(request):
#     # if not request.user.is_authenticated:
#     #     return redirect('%s?next=%s' % ('site/accounts:login', request.path))
#     user = User.objects.get(pk=request.user.pk)
#     if user.user_type == "customer":
#         if user.email_confirmed:
#             return redirect('index')
#         else:
#             return HttpResponse("<p>Please verify your account using the link sent to your email address</p>")
#
#     elif user.user_type == "staff":
#         return redirect('staff:panel')
#     elif user.user_type == 'seller':
#         return redirect('sellers:panel')
#     elif user.user_type == "admin":
#         return redirect('/michpastries-admin/')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            message = render_to_string('site/accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'hash': user.hash,
            })
            send_mail(
                subject,
                message,
                'info@' + split_domain_ports(request.get_host()),
                [user.email],
                fail_silently=False,
            )

            return redirect('accounts:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'site/accounts/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'site/accounts/account_activation_sent.html')


def activate(request, hash):
    try:

        user = User.objects.get(hash=hash)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None:
        user.is_active = True

        user.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('pages:panel')
    else:
        return render(request, 'site/accounts/account_activation_invalid.html')


def resettoken(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True

        user.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('accounts:panel')
    else:
        return render(request, 'site/accounts/account_activation_invalid.html')


@login_required(login_url='accounts:login')
def logout_view(request):
    Images.objects.filter(user=User.objects.get(pk=request.user.pk)).delete()
    logout(request)

    return redirect('accounts:login')


def edit_profile(request):
    return None


def forgot_password(request):
    if request.method == "POST":
        form = ForgotPasswordForm(request.POST)
        print(form.errors)
        if form.is_valid():
            try:
                user = User.objects.get(email=form.cleaned_data.get("email"))

                current_site = get_current_site(request)
                subject = 'Password Request Link'
                message = render_to_string('site/accounts/password_reset.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                send_mail(
                    subject,
                    message,
                    'info@' + split_domain_ports(request.get_host()),
                    [user.email],
                    fail_silently=False,
                )
                print("sent email")
                return render(request, 'site/accounts/reset-email-sent.html')
            except:
                print("user does not exist")
                messages.error(request, 'such an account does not exist')
                return redirect("accounts:forgot")


        else:
            print("did not send email due to invalid form")
            form = ForgotPasswordForm()
            return render(request, 'site/accounts/forgot.html', {'form': form})

    else:
        print("did not send email..just loaded the page")
        form = ForgotPasswordForm()
        return render(request, 'site/accounts/forgot.html', {'form': form})


def profile(request):
    return redirect('accounts:panel')


@login_required(login_url='accounts:login')
def create_profile(request):
    user = User.objects.get(pk=request.user.pk)
    signupform = ProfileAccountForm(
        initial={'first_name': user.first_name, 'last_name': user.last_name, 'email': user.email})

    if profile:
        print("profile ala")
        profile_form = ProfileForm(
            initial={'address': user.profile.address,
                     'mobile_money_phone_number': user.profile.mobile_money_phone_number,
                     'alternative_phone_number': user.profile.alternative_phone_number,
                     'location': user.profile.location}
        )
    else:
        profile_form = ProfileForm()

    if request.method == 'POST':
        signupform = ProfileAccountForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if profile_form.is_valid() and signupform.is_valid():
            signupform.save()
            obj = profile_form.save(commit=False)
            obj.save()
        else:
            print(profile_form.errors)
    context = {'cart_count': 0, 'form_profile': profile_form, 'form_signup': signupform, 'user': user}

    return render(request, 'site/accounts/profile.html', context)


def password_reset(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        form = NewPasswordForm()
        return render(request, 'site/accounts/password_reset_form.html', {'user': user, 'form': form})
    else:
        return render(request, 'site/accounts/account_activation_invalid.html')


def password_update(request):
    if request.method == "POST":
        form = NewPasswordForm(request.POST)
        print(form.errors)
        if form.is_valid():
            try:
                user = User.objects.get(hash=request.POST.get('user'))
                password = form.cleaned_data['password2']
                user.set_password(password)
                user.save()
                return redirect('accounts:login')
            except:
                print("user does not exist")
                messages.error(request, 'such an account does not exist')
                return redirect("accounts:forgot")


        else:
            print("did not send email due to invalid form")
            form = NewPasswordForm()
            return render(request, 'site/accounts/forgot.html', {'form': form})

    else:
        form = NewPasswordForm()
        return render(request, 'site/accounts/forgot.html', {'form': form})

templates/site/accounts/account_activation_email.html
{% load static %}
{% autoescape off %}
    Hi {{ user.email }},

    Please click on the link below to confirm your registration:
    http://{{ domain }}{% url 'accounts:activate' hash=hash %}


{% endautoescape %}

templates/site/accounts/account_activation_invalid.html
{% extends 'site/base.html' %}

{% block content %}
    <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

templates/site/accounts/account_activation_sent.html
{% extends 'site/base.html' %}

{% block maincontent %}
    <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

templates/site/accounts/forgot.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_extension %} Forgot  {% endblock %}
{#{% block nav %}{% endblock %}#}
{% block maincontent %}
    <section style="min-height: 100vh;color: white;">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-black text-left">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <div class="px-2" style="    background-color: rgba(0,122,0,0.99);border-radius: 6px;
">
                            <form method="post" action="{% url 'accounts:forgot' %}">

                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn btn-success ">Submit</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block footer %}{% endblock %}

templates/site/accounts/login.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extra %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block title_extension %} Login {% endblock %}
{% block maincontent %}
    <section style="min-height: 100vh;color: white;">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-black text-left">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <div class="px-2" style="    background-color: rgba(0,122,0,0.99);border-radius: 6px;
">
                            <form method="post"
                                  enctype="multipart/form-data">
                                <img src="https://img.icons8.com/material-sharp/96/000000/user-male-circle.png"/><br>

                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>    {% endfor %}
                                <button type="submit" class="btn btn-success ">Log in</button>
                                <a href="{% url 'accounts:signup' %}" class="btn btn-warning">Sign up</a>
                                <a href="{% url 'accounts:forgot' %}" style="color: white">Forgot password?</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block footer %}{% endblock %}

templates/site/accounts/password_form.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_extension %} Forgot {% endblock %}

{% block maincontent %}
    <section style="min-height: 100vh;color: white;">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-black text-left">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <div class="px-2" style="    background-color: rgba(0,122,0,0.99);border-radius: 6px;
">
                            <form method="post" action="{% url 'accounts:forgot' %}">
                                <input type="hidden" value="{{ user }} " name="user">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn btn-success ">Submit</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block footer %}{% endblock %}

templates/site/accounts/password_reset.html
{% load static %}
{% autoescape off %}
    Hi {{ user.email }},

    Please click on the link below to reset your password:
    http://{{ domain }}{% url 'accounts:password_reset' uidb64=uid token=token %}


{% endautoescape %}

templates/site/accounts/password_reset_form.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_extension %} password reset {% endblock %}

{% block maincontent %}
    <section style="min-height: 100vh;color: white;">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-black text-left">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <div class="px-2" style="    background-color: rgba(0,122,0,0.99);border-radius: 6px;
">
                            <form method="post" action="{% url 'accounts:password_update' %}">

                                {% csrf_token %}
                                <input name="user" value="{{ user.hash }}" type="hidden">
                                {% for field in form %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn btn-success ">Submit</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block footer %}{% endblock %}

templates/site/accounts/profile.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extra %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block title_extension %}{{ user }}{% endblock %}


{% block maincontent %}
    <div class="hero-wrap hero-bread" style="background-color: rgba(0,122,0,0.99)">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home</a></span>
                    </p>
                    <p class="mb-0 bread" style="text-transform: capitalize">Hi <span style="    font-family: 'Yellowtail';
">{{ user.first_name }} , You can Update your profile here</span></p>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section ftco-cart">
        <div class="container">
            <div class="card ">

                <div class="card-body">


                    <div class="tab-content">
                        <div class="tab-pane active" id="profile">

                            <form method="post" action="{% url 'accounts:createprofile' %}">
                                {% csrf_token %}
                                {% for field in form_signup %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>    {% endfor %}
                                <hr>
                                <hr>
                                {% for field in form_profile %}
                                    <div class="form-group ">
                                        {{ field|as_crispy_field }}
                                    </div>    {% endfor %}

                                <button type="submit" class="btn btn-success"> &nbspSubmit changes &nbsp</button>

                            </form>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

templates/site/accounts/reset-email-sent.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_extension %} Email sent {% endblock %}


{% block maincontent %}
    <p>Please confirm your email address to complete the reset process. </p>
{% endblock %}

templates/site/accounts/signup.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extra %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block title_extension %} Registration {% endblock %}
{% block maincontent %}
    <section style="min-height: 100vh;color: white;">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-black text-left">
                    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                        <div class="px-2" style="   background-color: rgba(0,122,0,0.99);border-radius: 6px;
">
                            <form method="post"
                                  action="{% url 'accounts:signup' %}">
                                <img src="https://img.icons8.com/material-sharp/96/000000/user-male-circle.png"/><br>

                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ next }}"/>
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-success">Register</button>
                                <a href="{% url 'accounts:login' %}" class="btn btn-warning">Log in</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block footer %}{% endblock %}